services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: user_java
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: user_java
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - ecommerce
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  ecommerce:
    driver: bridge

volumes:
  postgres:
    driver: local